/**
 * Comprehensive Indonesian Banking Directory
 * Full registry of 50+ central, regional, and digital banks across the 4 major
 * Indonesian banking sectors and geographic macro-regions.
 */

export type BankCategory = "bumn" | "swasta" | "bpd" | "digital";
export type BankRegion =
  "national" | "sumatera" | "jawa_bali" | "kalimantan_sulawesi" | "indonesia_timur";
export type CardNetwork = "gpn" | "visa" | "mastercard" | "jcb";

export interface IndonesianBank {
  code: string; // 3-digit clearing code
  name: string;
  shortName: string;
  category: BankCategory;
  region: BankRegion;
  supportedNetworks: CardNetwork[];
  accountLengths: number[];
  biFast: boolean;
  brandColor: string;
  swiftCode?: string;
  popular?: boolean;
}

export const INDONESIAN_BANKS: IndonesianBank[] = [
  // ── 1. Bank BUMN / Himbara (State-Owned National Banks) ─────────────────
  {
    code: "008",
    name: "Bank Mandiri",
    shortName: "Mandiri",
    category: "bumn",
    region: "national",
    supportedNetworks: ["gpn", "visa", "mastercard"],
    accountLengths: [13],
    biFast: true,
    brandColor: "#003D79",
    swiftCode: "BMRIIDJA",
    popular: true,
  },
  {
    code: "002",
    name: "Bank Rakyat Indonesia",
    shortName: "BRI",
    category: "bumn",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa"],
    accountLengths: [15],
    biFast: true,
    brandColor: "#00529C",
    swiftCode: "BRINIDJA",
    popular: true,
  },
  {
    code: "009",
    name: "Bank Negara Indonesia",
    shortName: "BNI",
    category: "bumn",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa", "jcb"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#006699",
    swiftCode: "BNINIDJA",
    popular: true,
  },
  {
    code: "200",
    name: "Bank Tabungan Negara",
    shortName: "BTN",
    category: "bumn",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [16],
    biFast: true,
    brandColor: "#003366",
    swiftCode: "BBTNIDJA",
    popular: false,
  },
  {
    code: "451",
    name: "Bank Syariah Indonesia",
    shortName: "BSI",
    category: "bumn",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#00A39D",
    swiftCode: "BSMDIDJA",
    popular: true,
  },

  // ── 2. Bank Swasta Nasional (Major Private Banks) ───────────────────────
  {
    code: "014",
    name: "Bank Central Asia",
    shortName: "BCA",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa", "jcb"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#0060AF",
    swiftCode: "CENAIDJA",
    popular: true,
  },
  {
    code: "022",
    name: "Bank CIMB Niaga",
    shortName: "CIMB Niaga",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa"],
    accountLengths: [10, 12, 13],
    biFast: true,
    brandColor: "#7D0000",
    swiftCode: "BNIAIDJA",
    popular: true,
  },
  {
    code: "011",
    name: "Bank Danamon",
    shortName: "Danamon",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#FF6600",
    swiftCode: "BDINIDJA",
    popular: false,
  },
  {
    code: "013",
    name: "Bank Permata",
    shortName: "Permata",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "visa", "mastercard"],
    accountLengths: [10, 16],
    biFast: true,
    brandColor: "#669900",
    swiftCode: "BBBAIDJA",
    popular: true,
  },
  {
    code: "019",
    name: "Bank Panin",
    shortName: "Panin",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#0055A5",
    swiftCode: "PINBIDJA",
    popular: false,
  },
  {
    code: "028",
    name: "Bank OCBC NISP",
    shortName: "OCBC",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa"],
    accountLengths: [12],
    biFast: true,
    brandColor: "#ED1B2D",
    swiftCode: "NISPIDJA",
    popular: false,
  },
  {
    code: "016",
    name: "Bank Maybank Indonesia",
    shortName: "Maybank",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "mastercard", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#FFC72C",
    swiftCode: "MAYBIDJA",
    popular: false,
  },
  {
    code: "426",
    name: "Bank Mega",
    shortName: "Mega",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#F47920",
    swiftCode: "MEGAIDJA",
    popular: false,
  },
  {
    code: "153",
    name: "Bank Sinarmas",
    shortName: "Sinarmas",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#E31B23",
    swiftCode: "SBINIDJA",
    popular: false,
  },
  {
    code: "213",
    name: "Bank BTPN / Jenius",
    shortName: "BTPN Jenius",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [11],
    biFast: true,
    brandColor: "#0099DA",
    swiftCode: "BTPNIDJA",
    popular: true,
  },
  {
    code: "536",
    name: "Bank BCA Syariah",
    shortName: "BCA Syariah",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "mastercard"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#004B87",
    popular: false,
  },
  {
    code: "147",
    name: "Bank Muamalat Indonesia",
    shortName: "Muamalat",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#5B2C6F",
    swiftCode: "MUAMIDJA",
    popular: false,
  },
  {
    code: "046",
    name: "Bank DBS Indonesia",
    shortName: "DBS",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#E4002B",
    swiftCode: "DBSIIDJA",
    popular: false,
  },
  {
    code: "023",
    name: "Bank UOB Indonesia",
    shortName: "UOB",
    category: "swasta",
    region: "national",
    supportedNetworks: ["gpn", "visa", "mastercard"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#0B2341",
    swiftCode: "UOVBIDJA",
    popular: false,
  },

  // ── 3. BPD (Bank Pembangunan Daerah) - 4 Regions ────────────────────────

  // Region 1: Sumatera
  {
    code: "118",
    name: "Bank Nagari (BPD Sumatera Barat)",
    shortName: "Bank Nagari",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#003A70",
    popular: false,
  },
  {
    code: "117",
    name: "Bank Sumut",
    shortName: "Bank Sumut",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn", "mastercard"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#D35400",
    popular: false,
  },
  {
    code: "119",
    name: "Bank Riau Kepri Syariah",
    shortName: "Bank Riau Kepri",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#1E8449",
    popular: false,
  },
  {
    code: "120",
    name: "Bank Sumsel Babel",
    shortName: "Bank Sumsel Babel",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#1B4F72",
    popular: false,
  },
  {
    code: "116",
    name: "Bank Aceh Syariah",
    shortName: "Bank Aceh",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#145A32",
    popular: false,
  },
  {
    code: "121",
    name: "Bank Lampung",
    shortName: "Bank Lampung",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#B7950B",
    popular: false,
  },
  {
    code: "133",
    name: "Bank Bengkulu",
    shortName: "Bank Bengkulu",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#78281F",
    popular: false,
  },
  {
    code: "115",
    name: "Bank Jambi",
    shortName: "Bank Jambi",
    category: "bpd",
    region: "sumatera",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#0E6251",
    popular: false,
  },

  // Region 2: Jawa & Bali
  {
    code: "110",
    name: "Bank BJB (BPD Jawa Barat & Banten)",
    shortName: "Bank BJB",
    category: "bpd",
    region: "jawa_bali",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#0066B3",
    popular: true,
  },
  {
    code: "111",
    name: "Bank DKI Jakarta",
    shortName: "Bank DKI",
    category: "bpd",
    region: "jawa_bali",
    supportedNetworks: ["gpn", "mastercard"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#E31E24",
    popular: true,
  },
  {
    code: "113",
    name: "Bank Jateng (BPD Jawa Tengah)",
    shortName: "Bank Jateng",
    category: "bpd",
    region: "jawa_bali",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#00838F",
    popular: false,
  },
  {
    code: "114",
    name: "Bank Jatim (BPD Jawa Timur)",
    shortName: "Bank Jatim",
    category: "bpd",
    region: "jawa_bali",
    supportedNetworks: ["gpn", "mastercard"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#C0392B",
    popular: false,
  },
  {
    code: "112",
    name: "Bank BPD DIY (Yogyakarta)",
    shortName: "BPD DIY",
    category: "bpd",
    region: "jawa_bali",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#4A235A",
    popular: false,
  },
  {
    code: "129",
    name: "Bank BPD Bali",
    shortName: "BPD Bali",
    category: "bpd",
    region: "jawa_bali",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#AF601A",
    popular: false,
  },

  // Region 3: Kalimantan & Sulawesi
  {
    code: "123",
    name: "Bank Kalbar (Kalimantan Barat)",
    shortName: "Bank Kalbar",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#117864",
    popular: false,
  },
  {
    code: "124",
    name: "Bank Kaltimtara (Kaltim & Kaltara)",
    shortName: "Bank Kaltimtara",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#1F618D",
    popular: false,
  },
  {
    code: "122",
    name: "Bank Kalsel (Kalimantan Selatan)",
    shortName: "Bank Kalsel",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#2874A6",
    popular: false,
  },
  {
    code: "125",
    name: "Bank Kalteng (Kalimantan Tengah)",
    shortName: "Bank Kalteng",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#196F3D",
    popular: false,
  },
  {
    code: "126",
    name: "Bank Sulselbar (Sulawesi Selatan & Barat)",
    shortName: "Bank Sulselbar",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#7D3C98",
    popular: false,
  },
  {
    code: "127",
    name: "Bank SulutGo (Sulawesi Utara & Gorontalo)",
    shortName: "Bank SulutGo",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#B9770E",
    popular: false,
  },
  {
    code: "134",
    name: "Bank Sulteng (Sulawesi Tengah)",
    shortName: "Bank Sulteng",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#2E4053",
    popular: false,
  },
  {
    code: "135",
    name: "Bank Sultra (Sulawesi Tenggara)",
    shortName: "Bank Sultra",
    category: "bpd",
    region: "kalimantan_sulawesi",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#21618C",
    popular: false,
  },

  // Region 4: Indonesia Timur (Nusa Tenggara, Maluku, Papua)
  {
    code: "128",
    name: "Bank NTB Syariah (Nusa Tenggara Barat)",
    shortName: "Bank NTB",
    category: "bpd",
    region: "indonesia_timur",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#117A65",
    popular: false,
  },
  {
    code: "130",
    name: "Bank NTT (Nusa Tenggara Timur)",
    shortName: "Bank NTT",
    category: "bpd",
    region: "indonesia_timur",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#884EA0",
    popular: false,
  },
  {
    code: "131",
    name: "Bank Maluku Malut (Maluku & Maluku Utara)",
    shortName: "Bank Maluku",
    category: "bpd",
    region: "indonesia_timur",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#2E86C1",
    popular: false,
  },
  {
    code: "132",
    name: "Bank Papua",
    shortName: "Bank Papua",
    category: "bpd",
    region: "indonesia_timur",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#17202A",
    popular: false,
  },

  // ── 4. Bank Digital & Neobanks (Modern Indonesian Digital Cards) ────────
  {
    code: "542",
    name: "Bank Jago",
    shortName: "Jago",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [12],
    biFast: true,
    brandColor: "#EC7B23",
    popular: true,
  },
  {
    code: "535",
    name: "SeaBank Indonesia",
    shortName: "SeaBank",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn", "mastercard"],
    accountLengths: [12],
    biFast: true,
    brandColor: "#F05323",
    popular: true,
  },
  {
    code: "567",
    name: "Allo Bank Indonesia",
    shortName: "Allo Bank",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#00B4D8",
    popular: false,
  },
  {
    code: "501",
    name: "Blu by BCA Digital",
    shortName: "Blu",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn", "mastercard"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#00A5CF",
    popular: true,
  },
  {
    code: "484",
    name: "Line Bank by Hana",
    shortName: "Line Bank",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#00C300",
    popular: false,
  },
  {
    code: "490",
    name: "Bank Neo Commerce (BNC)",
    shortName: "Neobank",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn", "mastercard"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#FFD600",
    popular: false,
  },
  {
    code: "459",
    name: "Krom Bank Indonesia",
    shortName: "Krom Bank",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#5E35B1",
    popular: false,
  },
  {
    code: "562",
    name: "Superbank Indonesia",
    shortName: "Superbank",
    category: "digital",
    region: "national",
    supportedNetworks: ["gpn", "visa"],
    accountLengths: [10],
    biFast: true,
    brandColor: "#2E7D32",
    popular: false,
  },
];

// Helper Lookups
export function getBankByCode(code: string): IndonesianBank | undefined {
  const c = code.trim().toUpperCase();
  return INDONESIAN_BANKS.find(
    (b) =>
      b.code === c ||
      b.code === c.padStart(3, "0") ||
      b.shortName.toUpperCase() === c ||
      b.name.toUpperCase() === c,
  );
}

export function getBankByName(nameOrShortName: string): IndonesianBank | undefined {
  const q = nameOrShortName
    .toLowerCase()
    .trim()
    .replace(/^bank\s+/, "");
  return INDONESIAN_BANKS.find((b) => {
    const bankNameClean = b.name.toLowerCase().replace(/^bank\s+/, "");
    const bankShortClean = b.shortName.toLowerCase().replace(/^bank\s+/, "");
    return (
      bankNameClean === q ||
      bankShortClean === q ||
      b.name.toLowerCase() === nameOrShortName.toLowerCase().trim() ||
      b.shortName.toLowerCase() === nameOrShortName.toLowerCase().trim()
    );
  });
}

export function getBanksByCategory(category: BankCategory): IndonesianBank[] {
  return INDONESIAN_BANKS.filter((b) => b.category === category);
}

export function getBanksByRegion(region: BankRegion): IndonesianBank[] {
  return INDONESIAN_BANKS.filter((b) => b.region === region);
}

export function searchBanks(query: string): IndonesianBank[] {
  const q = query.toLowerCase().trim();
  if (!q) return INDONESIAN_BANKS;
  return INDONESIAN_BANKS.filter(
    (b) =>
      b.name.toLowerCase().includes(q) ||
      b.shortName.toLowerCase().includes(q) ||
      b.code.includes(q) ||
      b.category.toLowerCase().includes(q) ||
      b.region.toLowerCase().includes(q),
  );
}
