import { NextResponse } from "next/server";
import { FlaggedTransaction } from "@/lib/fraud-detection";

const mockFlaggedTransactions: FlaggedTransaction[] = [
  {
    id: "tx-8819",
    orderNumber: "ORD-2026-9901",
    amount: 1420.0,
    currency: "USD",
    customerName: "Alex Vance",
    customerEmail: "a.vance@blackmesa.org",
    ipAddress: "194.26.29.11",
    country: "DE",
    riskScore: 88,
    recommendation: "MANUAL_REVIEW",
    status: "FLAGGED",
    riskFactors: {
      velocityScore: 92,
      geoMismatchScore: 85,
      proxyTorVpn: true,
      cardBinMismatch: true,
      deviceFingerprintRisk: 78,
      behavioralAnomalyScore: 80,
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    hasDossier: true,
  },
  {
    id: "tx-8820",
    orderNumber: "ORD-2026-9902",
    amount: 320.5,
    currency: "USD",
    customerName: "Budi Santoso",
    customerEmail: "budi.s@techasia.id",
    ipAddress: "103.111.202.14",
    country: "ID",
    riskScore: 22,
    recommendation: "AUTO_APPROVE",
    status: "CLEARED",
    riskFactors: {
      velocityScore: 12,
      geoMismatchScore: 8,
      proxyTorVpn: false,
      cardBinMismatch: false,
      deviceFingerprintRisk: 15,
      behavioralAnomalyScore: 10,
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    hasDossier: false,
  },
  {
    id: "tx-8821",
    orderNumber: "ORD-2026-9903",
    amount: 2890.0,
    currency: "USD",
    customerName: "Anonymous Carder",
    customerEmail: "temp9921@sharklasers.com",
    ipAddress: "185.220.101.5",
    country: "RU",
    riskScore: 96,
    recommendation: "AUTO_VOID",
    status: "VOIDED",
    riskFactors: {
      velocityScore: 98,
      geoMismatchScore: 95,
      proxyTorVpn: true,
      cardBinMismatch: true,
      deviceFingerprintRisk: 90,
      behavioralAnomalyScore: 94,
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 82).toISOString(),
    hasDossier: true,
  },
  {
    id: "tx-8822",
    orderNumber: "ORD-2026-9904",
    amount: 540.0,
    currency: "USD",
    customerName: "Elena Rostova",
    customerEmail: "elena.r@fintech-global.eu",
    ipAddress: "84.17.45.201",
    country: "FR",
    riskScore: 68,
    recommendation: "CHALLENGE_3DS",
    status: "FLAGGED",
    riskFactors: {
      velocityScore: 65,
      geoMismatchScore: 62,
      proxyTorVpn: false,
      cardBinMismatch: true,
      deviceFingerprintRisk: 55,
      behavioralAnomalyScore: 60,
    },
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    hasDossier: false,
  },
];

export async function GET() {
  return NextResponse.json(mockFlaggedTransactions);
}
